---
title: "Cross Validation"
output: github_document
---

```{r setup}
library(tidyverse)
library(modelr)
library(mgcv)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() +  theme(legend.position = "bottom"))

options(
  ggplots2.continuous.color = "viridis",
  ggplots2.continuous.fill = "viridus"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Simulate data
```{r}
set.seed(1)
nonlin_df = 
  tibble(
    id = 1:100,
    x = runif(100, 0, 1),
    y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
  )

nonlin_df %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point()
```

## Cross validation -- by hand

Get training and testing datasets
```{r}
train_df = sample_n(nonlin_df, size = 80)
test_df = anti_join(nonlin_df, train_df, by = "id") # the rest 20 data are test_df use anti_joint
```

fit three models.
```{r}
linear_mod = lm(y ~ x, data = train_df)
smooth_mod = gam(y ~ s(x), data = train_df)
wiggly_mod = gam(y ~ s(x, k=30), sp = 10e-6, data = train_df)
```

can I see what I just did ...
```{r}
train_df %>% 
  gather_predictions(linear_mod, smooth_mod, wiggly_mod) %>% 
  ggplot(aes(x =x ,y = y)) +
  geom_point() +
  geom_line(aes(y = pred), color = "red") +
  facet_grid(. ~ model)
```
From the plot, linear and wiggly bad prediction and smooth model good prediction. 


Look at prediction accuracy.
```{r}
rmse(linear_mod, test_df) # root mean square error
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)
```


```{r}

```



