---
title: "Linear models"
output: github_document
---

```{r setup}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() +  theme(legend.position = "bottom"))

options(
  ggplots2.continuous.color = "viridis",
  ggplots2.continuous.fill = "viridus"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Import data

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type)
```


## Fit a model
```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) +
  geom_point()
```


Let's fit the model we care about.
```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

Let's look at the results...

```{r, include=FALSE}
fit
summary(fit) #a matrix
summary(fit)$coef %>% class ## only get coefficient 
coef(fit)
residuals(fit)
```

Let's look at the results better ...
```{r}
broom::glance(fit)

broom::tidy(fit) %>%   # a data frame
select(-std.error, -statistic) %>% 
  mutate(
    term = str_replace(term, "borough", "Borough: ")
  ) %>% 
  knitr::kable(digits = 3)
```

## Be in control of factors
```{r}
nyc_airbnb =
  nyc_airbnb %>% 
  mutate(
    borough = fct_infreq(borough), # order by frequency of the borough
    room_type = fct_infreq(room_type)
         )
```


Look at the plot again
```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) +
  geom_point()
```
Change the reference group to Manhattan instead of Bronx

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)

broom::tidy(fit)
broom::glance(fit)
```


## Diagnostics

```{r}
nyc_airbnb %>% 
modelr::add_residuals(fit) %>% 
  ggplot(aes(x = borough, y = resid)) +
  geom_violin() +
  ylim(-500, 1500)

nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = stars, y = resid)) +
  geom_point() +
  facet_wrap(.~borough) # show each borough's plot
```

## Hypothesis tests

This does t-test by default
```{r}
fit %>% 
  broom::tidy() 
```

What about the significance of `borough`
```{r}
fit_null = lm(price ~ stars, data = nyc_airbnb) # if borugh unassociated with price is true
fit_alt = lm(price ~ stars + borough, data = nyc_airbnb)

anova(fit_null, fit_alt) %>% 
  broom::tidy()
```


